-- AMBIENTES
DELIMITER //
CREATE PROCEDURE findAllAmbientes()
BEGIN
    SELECT ID_AMBIENTES, CANT_SILLAS, CANT_MESAS, NUM_APRENDICES, NUM_EQUIPOS
    FROM ambientes;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findAmbientes(IN _ID INT)
BEGIN
    SELECT ID_AMBIENTES, CANT_SILLAS, CANT_MESAS, NUM_APRENDICES, NUM_EQUIPOS
    FROM ambientes
    WHERE ID_AMBIENTES = _ID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE insertAmbientes(IN _ID INT, IN _CANT_SILLAS INT, IN _CANT_MESAS INT, IN _NUM_APRENDICES INT, IN _NUM_EQUIPOS INT)
BEGIN
    INSERT INTO ambientes (ID_AMBIENTES, CANT_SILLAS, CANT_MESAS, NUM_APRENDICES, NUM_EQUIPOS)
    VALUES (_ID, _CANT_SILLAS, _CANT_MESAS, _NUM_APRENDICES, _NUM_EQUIPOS);
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE updateAmbientes(IN _ID INT, IN _CANT_SILLAS INT, IN _CANT_MESAS INT, IN _NUM_APRENDICES INT, IN _NUM_EQUIPOS INT)
BEGIN
    UPDATE ambientes
    SET CANT_SILLAS = _CANT_SILLAS, CANT_MESAS = _CANT_MESAS, NUM_APRENDICES = _NUM_APRENDICES, NUM_EQUIPOS = _NUM_EQUIPOS
    WHERE ID_AMBIENTES = _ID;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE deleteAmbientes(IN _ID INT)
BEGIN
    DELETE FROM ambientes
    WHERE ID_AMBIENTES = _ID;
END //
DELIMITER ;



-- INVENTARIO
DELIMITER //
CREATE PROCEDURE findAllInventario()
BEGIN
    SELECT ID_INVENTARIO, CANTIDAD, FECHA_REGISTRO, ESTADO, ID_COMPUTADOR, ID_HERRAMIENTA, ID_AMBIENTES, ID_MATERIAL
    FROM inventario;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE findInventario(IN _ID_INVENTARIO INT)
BEGIN
    SELECT ID_INVENTARIO, CANTIDAD, FECHA_REGISTRO, ESTADO, ID_COMPUTADOR, ID_HERRAMIENTA, ID_AMBIENTES, ID_MATERIAL
    FROM inventario
    WHERE ID_INVENTARIO = _ID_INVENTARIO;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE insertInventario(IN _ID_INVENTARIO INT, IN _CANTIDAD INT, IN _FECHA_REGISTRO DATE, IN _ESTADO TINYINT, IN _ID_COMPUTADOR INT, IN _ID_HERRAMIENTA INT, IN _ID_AMBIENTES INT, IN _ID_MATERIAL INT)
BEGIN
    INSERT INTO inventario (ID_INVENTARIO, CANTIDAD, FECHA_REGISTRO, ESTADO, ID_COMPUTADOR, ID_HERRAMIENTA, ID_AMBIENTES, ID_MATERIAL)
    VALUES (_ID_INVENTARIO, _CANTIDAD, _FECHA_REGISTRO, _ESTADO, _ID_COMPUTADOR, _ID_HERRAMIENTA, _ID_AMBIENTES, _ID_MATERIAL);
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE updateInventario(IN _ID_INVENTARIO INT, IN _CANTIDAD INT, IN _FECHA_REGISTRO DATE, IN _ESTADO TINYINT, IN _ID_COMPUTADOR INT, IN _ID_HERRAMIENTA INT, IN _ID_AMBIENTES INT, IN _ID_MATERIAL INT)
BEGIN
    UPDATE inventario
    SET CANTIDAD = _CANTIDAD, FECHA_REGISTRO = _FECHA_REGISTRO, ESTADO = _ESTADO, ID_COMPUTADOR = _ID_COMPUTADOR, ID_HERRAMIENTA = _ID_HERRAMIENTA, ID_AMBIENTES = _ID_AMBIENTES, ID_MATERIAL = _ID_MATERIAL
    WHERE ID_INVENTARIO = _ID_INVENTARIO;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE deleteInventario(IN _ID_INVENTARIO INT)
BEGIN
    DELETE FROM inventario
    WHERE ID_INVENTARIO = _ID_INVENTARIO;
END //
DELIMITER ;



-- COMPUTADOR

DELIMITER //
CREATE PROCEDURE findAllComputador()
BEGIN
    SELECT ID_COMPUTADOR, MARCA, CARGADOR, MOUSE
    FROM computador;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findComputador(IN _ID_COMPUTADOR INT)
BEGIN
    SELECT ID_COMPUTADOR, MARCA, CARGADOR, MOUSE
    FROM computador
    WHERE ID_COMPUTADOR = _ID_COMPUTADOR;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE insertComputador(IN _ID_COMPUTADOR INT, IN _MARCA VARCHAR(100), IN _CARGADOR VARCHAR(10), IN _MOUSE VARCHAR(10))
BEGIN
    INSERT INTO computador (ID_COMPUTADOR, MARCA, CARGADOR, MOUSE)
    VALUES (_ID_COMPUTADOR, _MARCA, _CARGADOR, _MOUSE);
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE updateComputador(IN _ID_COMPUTADOR INT, IN _MARCA VARCHAR(100), IN _CARGADOR VARCHAR(10), IN _MOUSE VARCHAR(10))
BEGIN
    UPDATE computador
    SET MARCA = _MARCA, CARGADOR = _CARGADOR, MOUSE = _MOUSE
    WHERE ID_COMPUTADOR = _ID_COMPUTADOR;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE deleteComputador(IN _ID_COMPUTADOR INT)
BEGIN
    DELETE FROM computador
    WHERE ID_COMPUTADOR = _ID_COMPUTADOR;
END //
DELIMITER ;
-- MATERIAL
DELIMITER //
CREATE PROCEDURE findAllMaterial()
BEGIN
    SELECT ID_MATERIAL, TIPO, COLOR, MEDIDAS
    FROM material;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findMaterial(IN _ID_MATERIAL INT)
BEGIN
    SELECT ID_MATERIAL, TIPO, COLOR, MEDIDAS
    FROM material
    WHERE ID_MATERIAL = _ID_MATERIAL;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE insertMaterial(IN _ID_MATERIAL INT, IN _TIPO VARCHAR(100), IN _COLOR VARCHAR(10), IN _MEDIDAS VARCHAR(10))
BEGIN
    INSERT INTO material (ID_MATERIAL, TIPO, COLOR, MEDIDAS)
    VALUES (_ID_MATERIAL, _TIPO, _COLOR, _MEDIDAS);
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE updateMaterial(IN _ID_MATERIAL INT, IN _TIPO VARCHAR(100), IN _COLOR VARCHAR(10), IN _MEDIDAS VARCHAR(10))
BEGIN
    UPDATE material
    SET TIPO = _TIPO, COLOR = _COLOR, MEDIDAS = _MEDIDAS
    WHERE ID_MATERIAL = _ID_MATERIAL;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE deleteMaterial(IN _ID_MATERIAL INT)
BEGIN
    DELETE FROM material
    WHERE ID_MATERIAL = _ID_MATERIAL;
END //
DELIMITER ;


--PRESTAMOS
DELIMITER //
CREATE PROCEDURE findAllPrestamos()
BEGIN
    SELECT ID_PRESTAMOS, FECHA_PRESTAMO, FINAL_PRESTAMO, OBSERVACIONES, ID_USUARIO
    FROM prestamos;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findPrestamos(IN _ID_PRESTAMOS INT)
BEGIN
    SELECT ID_PRESTAMOS, FECHA_PRESTAMO, FINAL_PRESTAMO, OBSERVACIONES, ID_USUARIO
    FROM prestamos
    WHERE ID_PRESTAMOS = _ID_PRESTAMOS;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE insertPrestamos(IN _ID_PRESTAMOS INT, IN _FECHA_PRESTAMO DATE, IN _FINAL_PRESTAMO DATE, IN _OBSERVACIONES VARCHAR(100), IN _ID_USUARIO INT)
BEGIN
    INSERT INTO prestamos (ID_PRESTAMOS, FECHA_PRESTAMO, FINAL_PRESTAMO, OBSERVACIONES, ID_USUARIO)
    VALUES (_ID_PRESTAMOS, _FECHA_PRESTAMO, _FINAL_PRESTAMO, _OBSERVACIONES, _ID_USUARIO);
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE updatePrestamos(IN _ID_PRESTAMOS INT, IN _FECHA_PRESTAMO DATE, IN _FINAL_PRESTAMO DATE, IN _OBSERVACIONES VARCHAR(100), IN _ID_USUARIO INT)
BEGIN
    UPDATE prestamos
    SET FECHA_PRESTAMO = _FECHA_PRESTAMO, FINAL_PRESTAMO = _FINAL_PRESTAMO, OBSERVACIONES = _OBSERVACIONES, ID_USUARIO = _ID_USUARIO
    WHERE ID_PRESTAMOS = _ID_PRESTAMOS;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE deletePrestamos(IN _ID_PRESTAMOS INT)
BEGIN
    DELETE FROM prestamos
    WHERE ID_PRESTAMOS = _ID_PRESTAMOS;
END //
DELIMITER ;


--RESERVAS

DELIMITER //
CREATE PROCEDURE findAllReserva()
BEGIN
    SELECT ID_RESERVA, FECHA_RES, HORA_RES, TIEMPO_REQUERIDO, ID_USUARIO
    FROM reserva;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE findReserva(IN _ID_RESERVA INT)
BEGIN
    SELECT ID_RESERVA, FECHA_RES, HORA_RES, TIEMPO_REQUERIDO, ID_USUARIO
    FROM reserva
    WHERE ID_RESERVA = _ID_RESERVA;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE insertReserva(IN _ID_RESERVA INT, IN _FECHA_RES DATE, IN _HORA_RES TIME, IN _TIEMPO_REQUERIDO TIME, IN _ID_USUARIO INT)
BEGIN
    INSERT INTO reserva (ID_RESERVA, FECHA_RES, HORA_RES, TIEMPO_REQUERIDO, ID_USUARIO)
    VALUES (_ID_RESERVA, _FECHA_RES, _HORA_RES, _TIEMPO_REQUERIDO, _ID_USUARIO);
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE updateReserva(IN _ID_RESERVA INT, IN _FECHA_RES DATE, IN _HORA_RES TIME, IN _TIEMPO_REQUERIDO TIME, IN _ID_USUARIO INT)
BEGIN
    UPDATE reserva
    SET FECHA_RES = _FECHA_RES, HORA_RES = _HORA_RES, TIEMPO_REQUERIDO = _TIEMPO_REQUERIDO, ID_USUARIO = _ID_USUARIO
    WHERE ID_RESERVA = _ID_RESERVA;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE deleteReserva(IN _ID_RESERVA INT)
BEGIN
    DELETE FROM reserva
    WHERE ID_RESERVA = _ID_RESERVA;
END //
DELIMITER ;


--RES_ELEM
DELIMITER //
CREATE PROCEDURE findAllResElem()
BEGIN
    SELECT ID_RES_ELEM, ID_RESERVA, ID_INVENTARIO
    FROM res_elem;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findResElem(IN _ID_RES_ELEM INT)
BEGIN
    SELECT ID_RES_ELEM, ID_RESERVA, ID_INVENTARIO
    FROM res_elem
    WHERE ID_RES_ELEM = _ID_RES_ELEM;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE insertResElem(IN _ID_RES_ELEM INT, IN _ID_RESERVA INT, IN _ID_INVENTARIO INT)
BEGIN
    INSERT INTO res_elem (ID_RES_ELEM, ID_RESERVA, ID_INVENTARIO)
    VALUES (_ID_RES_ELEM, _ID_RESERVA, _ID_INVENTARIO);
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE updateResElem(IN _ID_RES_ELEM INT, IN _ID_RESERVA INT, IN _ID_INVENTARIO INT)
BEGIN
    UPDATE res_elem
    SET ID_RESERVA = _ID_RESERVA, ID_INVENTARIO = _ID_INVENTARIO
    WHERE ID_RES_ELEM = _ID_RES_ELEM;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE deleteResElem(IN _ID_RES_ELEM INT)
BEGIN
    DELETE FROM res_elem
    WHERE ID_RES_ELEM = _ID_RES_ELEM;
END //
DELIMITER ;


-- ROL
DELIMITER //
CREATE PROCEDURE findAllRol()
BEGIN
    SELECT ID_ROL, NOMBRE_ROL, ESTADO
    FROM rol;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findRol(IN _ID_ROL INT)
BEGIN
    SELECT ID_ROL, NOMBRE_ROL, ESTADO
    FROM rol
    WHERE ID_ROL = _ID_ROL;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE insertRol(IN _ID_ROL INT, IN _NOMBRE_ROL VARCHAR(100), IN _ESTADO TINYINT)
BEGIN
    INSERT INTO rol (ID_ROL, NOMBRE_ROL, ESTADO)
    VALUES (_ID_ROL, _NOMBRE_ROL, _ESTADO);
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE updateRol(IN _ID_ROL INT, IN _NOMBRE_ROL VARCHAR(100), IN _ESTADO TINYINT)
BEGIN
    UPDATE rol
    SET NOMBRE_ROL = _NOMBRE_ROL, ESTADO = _ESTADO
    WHERE ID_ROL = _ID_ROL;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE deleteRol(IN _ID_ROL INT)
BEGIN
    DELETE FROM rol
    WHERE ID_ROL = _ID_ROL;
END //
DELIMITER ;


-- USUARIOS

DELIMITER //
CREATE PROCEDURE findAllUsuario()
BEGIN
    SELECT ID_USUARIO, NOMBRE, APELLIDO, TIPO_DOCUMENTO, NUM_DOCUMENTO, CORREO, TELEFONO, DIRECCION, JORNADA, PROGRAMA_FORMACION, NUM_FICHA, GENERO, CONTRASENA, ID_ROL
    FROM usuario;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE findUsuario(IN _ID_USUARIO INT)
BEGIN
    SELECT ID_USUARIO, NOMBRE, APELLIDO, TIPO_DOCUMENTO, NUM_DOCUMENTO, CORREO, TELEFONO, DIRECCION, JORNADA, PROGRAMA_FORMACION, NUM_FICHA, GENERO, CONTRASENA, ID_ROL
    FROM usuario
    WHERE ID_USUARIO = _ID_USUARIO;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE insertUsuario(IN _ID_USUARIO INT, IN _NOMBRE VARCHAR(30), IN _APELLIDO VARCHAR(30), IN _TIPO_DOCUMENTO VARCHAR(3), IN _NUM_DOCUMENTO INT, IN _CORREO VARCHAR(30), IN _TELEFONO VARCHAR(12), IN _DIRECCION VARCHAR(30), IN _JORNADA VARCHAR(30), IN _PROGRAMA_FORMACION VARCHAR(100), IN _NUM_FICHA INT, IN _GENERO VARCHAR(10), IN _CONTRASENA VARCHAR(100), IN _ID_ROL INT)
BEGIN
    INSERT INTO usuario (ID_USUARIO, NOMBRE, APELLIDO, TIPO_DOCUMENTO, NUM_DOCUMENTO, CORREO, TELEFONO, DIRECCION, JORNADA, PROGRAMA_FORMACION, NUM_FICHA, GENERO, CONTRASENA, ID_ROL)
    VALUES (_ID_USUARIO, _NOMBRE, _APELLIDO, _TIPO_DOCUMENTO, _NUM_DOCUMENTO, _CORREO, _TELEFONO, _DIRECCION, _JORNADA, _PROGRAMA_FORMACION, _NUM_FICHA, _GENERO, _CONTRASENA, _ID_ROL);
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE updateUsuario(IN _ID_USUARIO INT, IN _NOMBRE VARCHAR(30), IN _APELLIDO VARCHAR(30), IN _TIPO_DOCUMENTO VARCHAR(3), IN _NUM_DOCUMENTO INT, IN _CORREO VARCHAR(30), IN _TELEFONO VARCHAR(12), IN _DIRECCION VARCHAR(30), IN _JORNADA VARCHAR(30), IN _PROGRAMA_FORMACION VARCHAR(100), IN _NUM_FICHA INT, IN _GENERO VARCHAR(10), IN _CONTRASENA VARCHAR(100), IN _ID_ROL INT)
BEGIN
    UPDATE usuario
    SET NOMBRE = _NOMBRE, APELLIDO = _APELLIDO, TIPO_DOCUMENTO = _TIPO_DOCUMENTO, NUM_DOCUMENTO = _NUM_DOCUMENTO, CORREO = _CORREO, TELEFONO = _TELEFONO, DIRECCION = _DIRECCION, JORNADA = _JORNADA, PROGRAMA_FORMACION = _PROGRAMA_FORMACION, NUM_FICHA = _NUM_FICHA, GENERO = _GENERO, CONTRASENA = _CONTRASENA, ID_ROL = _ID_ROL
    WHERE ID_USUARIO = _ID_USUARIO;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE deleteUsuario(IN _ID_USUARIO INT)
BEGIN
    DELETE FROM usuario
    WHERE ID_USUARIO = _ID_USUARIO;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE findAllElementos()
BEGIN
    SELECT ID_ELEMENTOS, ESTADO_ACTUAL, ID_PRESTAMOS, ID_INVENTARIO
    FROM elementos;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE findElementos(IN _ID_ELEMENTO INT)
BEGIN
    SELECT ID_ELEMENTOS, ESTADO_ACTUAL, ID_PRESTAMOS, ID_INVENTARIO
    FROM elementos
    WHERE ID_ELEMENTOS = _ID_ELEMENTO;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE insertElementos(IN _ID_ELEMENTO INT, IN _ESTADO_ACTUAL TINYINT, IN _ID_PRESTAMOS INT, IN _ID_INVENTARIO INT)
BEGIN
    INSERT INTO elementos (ID_ELEMENTOS, ESTADO_ACTUAL, ID_PRESTAMOS, ID_INVENTARIO)
    VALUES (_ID_ELEMENTO, _ESTADO_ACTUAL, _ID_PRESTAMOS, _ID_INVENTARIO);
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE updateElementos(IN _ID_ELEMENTO INT, IN _ESTADO_ACTUAL TINYINT, IN _ID_PRESTAMOS INT, IN _ID_INVENTARIO INT)
BEGIN
    UPDATE elementos
    SET ESTADO_ACTUAL = _ESTADO_ACTUAL, ID_PRESTAMOS = _ID_PRESTAMOS, ID_INVENTARIO = _ID_INVENTARIO
    WHERE ID_ELEMENTOS = _ID_ELEMENTO;
END //
DELIMITER ;
DELIMITER //
CREATE PROCEDURE deleteElementos(IN _ID_ELEMENTO INT)
BEGIN
    DELETE FROM elementos
    WHERE ID_ELEMENTOS = _ID_ELEMENTO;
END //
DELIMITER ;
